# Database connection using connection string
DATABASE_URL = "paste_your_database_url"

# Host for the database
db_host = "db_host"
# Admin password for URL management
admin_password = "admin_password"
